<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="frmBankSetupInfo.aspx.cs" Inherits="frmBankSetupInfo" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
 <script language="javascript" type="text/javascript" >

     function isNumber(evt) {
         evt = (evt) ? evt : window.event;
         var charCode = (evt.which) ? evt.which : evt.keyCode;
         if (charCode != 46 && charCode > 31
            && (charCode < 48 || charCode > 57)) {
             return false;
         }
         return true;
     }

     

     function LoadModalDiv() {

         var bcgDiv = document.getElementById("divBackground");
         bcgDiv.style.display = "block";

     }
     function HideModalDiv() {

         var bcgDiv = document.getElementById("divBackground");
         bcgDiv.style.display = "none";

     }
   
</script>
<div></div>
    <div id="frmMainDiv" style="background-color:White; width:100%;">
    <table   id="pageFooterWrapper" >
        <tr>
            <td align="center" style="width:15%; vertical-align:middle;">
                <asp:Button  ID="BtnDeletess" runat="server"  ToolTip="Delete Record"  TabIndex="903" 
                             onclientclick="javascript:return window.confirm('are u really want to delete these data')"             
                             Text="Delete"
                             Width="110px" Height="35px" BorderStyle="Outset" BorderWidth="1px" 
                             onclick="BtnDelete_Click" /></td>
            <td align="center" style="width:15%; vertical-align:middle;">
                <asp:Button ID="BtnSavess" 
                            runat="server" ToolTip="Save or Update Record" TabIndex="901" Text="Save"             
                            Width="110px" Height="35px" BorderStyle="Outset" BorderWidth="1px" 
                            onclick="BtnSave_Click"/></td>
            <td align="center" style="width:15%; vertical-align:middle;">
                <asp:Button ID="BtnReset" runat="server" ToolTip="Clear Form" TabIndex="904"   
                            Text="Clear" 
                            Width="110px" Height="35px" BorderStyle="Outset" BorderWidth="1px" 
                            onclick="BtnReset_Click" />
            </td>              
        </tr>
    </table>
<table style="width:100%;">
<tr>
<td style="width:10%; height: 10px;"></td>
<td style="width:80%; padding-top:10px; height: 10px;" align="center"> 
    </td>
<td style="width:10%; height: 10px;"></td>
</tr>
<tr>
<td style="width:1%;"></td>
<td style="width:2%; padding-top:10px;" align="center"> 
<table style="width:100%;">
<tr>
<td style="width:18%; " align="left" valign="top">
<%--<asp:UpdatePanel ID="UpdatePanel1" runat="server" UpdateMode="Always">
<ContentTemplate>--%>
<%--<asp:Label ID="Label4" runat="server" Text="Select Option" Font-Bold="True" 
        ForeColor="#CC3300"></asp:Label>--%>
<fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;line-height:2.5em;"><legend style="color: maroon;"><b>Select Option</b></legend>
<asp:Panel ID="pnlTreeView" runat="server" Width="290px" ScrollBars="Auto" Height="200px">
    <asp:TreeView ID="TreeView1" runat="server" AutoGenerateDataBindings="False" Width="100%"
             onselectednodechanged="TreeView1_SelectedNodeChanged" ImageSet="Msdn"
        ForeColor="Blue" ParentNodeStyle-ForeColor="Green" Font-Bold="True">
        <ParentNodeStyle ForeColor="Green" />
        <SelectedNodeStyle Font-Underline="False" HorizontalPadding="3px" 
                VerticalPadding="2px" BackColor="White" BorderColor="#888888" 
                BorderStyle="Solid" BorderWidth="1px" />
        <Nodes>
            <asp:TreeNode Text="Bank Setup" Value="BankSetup"></asp:TreeNode>
            <asp:TreeNode Text="Branch Setup" Value="BranchSetup"></asp:TreeNode>
        </Nodes>
        <NodeStyle Font-Size="8pt" ForeColor="Black" HorizontalPadding="2px" 
                NodeSpacing="2px" VerticalPadding="3px" Font-Names="Verdana" />
    </asp:TreeView>
</asp:Panel>
</fieldset>
<%--</ContentTemplate>
</asp:UpdatePanel>--%>
</td>
<td style="width:1%;"></td>
<td style="width:60%;  vertical-align:top;" align="left">
 <fieldset style="vertical-align: top; border: solid 1px #8BB381;text-align:left;"><legend style="color: maroon;">
     <b>Bank/Branch Information </b></legend>
<div>
<%--<asp:UpdatePanel ID="UpdatePanel2" runat="server">
<ContentTemplate>--%>
<%--<asp:Label ID="lblName" runat="server" Text="Department/Type Information" 
        Font-Bold="True" ForeColor="#CC3300"></asp:Label>--%>
       
<asp:Panel ID="pnlBank" runat="server">
<table style=" width:100%;">    
	<tr >
	<td style="width: 19%;" align="left">
	    <asp:Label ID="lblSegDesc" runat="server" Font-Size="9pt">Bank Name</asp:Label>
        </td>
	<td align="left" colspan="4">
        <asp:TextBox ID="txtBankName" runat="server" CssClass="tbl" Font-Size="8pt" 
            MaxLength="50" SkinID="tbPlain" TabIndex="2" Width="100%"></asp:TextBox>
        </td>       
    </tr>
    
    <tr>
        <td align="left" style="width: 19%;">
            <asp:Label ID="lblSegCode0" runat="server" Font-Size="8pt">Segment Code</asp:Label>
        </td>
        <td align="left" style="width: 31%;">
            <asp:TextBox ID="txtSegCode" runat="server" AutoPostBack="False" 
                Font-Size="8pt" MaxLength="7" SkinID="tbGray" Width="95%"></asp:TextBox>
        </td>
        <td style="width: 4%;">
            <asp:TextBox ID="txtBankId" runat="server" CssClass="tbc" Font-Size="8pt" 
                MaxLength="2" SkinID="tbPlain" TabIndex="1" Visible="False" Width="100%"></asp:TextBox>
        </td>
        <td align="left" style="width: 20%;">
            <asp:Label ID="lblParentCode0" runat="server" Font-Size="8pt">Parent Code</asp:Label>
        </td>
        <td align="left" style="width: 25%;">
            <asp:TextBox ID="txtParentCode" runat="server" AutoPostBack="False" 
                Font-Size="8pt" MaxLength="7" SkinID="tbGray" Width="95%"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td align="left" style="width: 19%;">
            &nbsp;</td>
        <td align="left" colspan="4">
        </td>
    </tr>
</table>
</asp:Panel>

<asp:Panel ID="pnlBranch" runat="server">
                    <table style="width: 100%">
                        <tr>
                            <td style="width:21%; height: 22px;" align="right">
                                &nbsp;</td>
                            <td align="left" colspan="4" style="height: 22px">
                                <asp:RadioButtonList ID="rdbBankType" runat="server" 
                                    RepeatDirection="Horizontal">
                                    <asp:ListItem Selected="True" Value="B">Bank</asp:ListItem>
                                    <asp:ListItem Value="M">Mobile Bank</asp:ListItem>
                                    <asp:ListItem Value="C">Card Visa/Masters</asp:ListItem>
                                </asp:RadioButtonList>
                                </td>
                        </tr>
                        
                        <tr>
                            <td align="right" style="width:21%; height: 22px;">
                                <asp:HiddenField ID="hfBranchID" runat="server" />
                                <asp:Label ID="lblSegDesc0" runat="server" Font-Size="9pt">Bank Name :</asp:Label>
                            </td>
                            <td align="left" colspan="4" style="height: 22px">
                                <asp:DropDownList ID="ddlBankName" runat="server" AutoPostBack="True" 
                                    Font-Size="8pt" Height="26px" 
                                    onselectedindexchanged="ddlBankName_SelectedIndexChanged" SkinID="ddlPlain" 
                                    Width="100%">
                                </asp:DropDownList>
                            </td>
                        </tr>
                        
                        <tr>
                            <td align="right" style="width:21%; height: 27px;">
                                <asp:Label ID="lblSegDesc1" runat="server" Font-Size="9pt">Branch Name :</asp:Label>
                            </td>
                            <td align="left" colspan="2" style="height: 27px;">
                                <asp:TextBox ID="txtBranchName" runat="server" Width="100%"></asp:TextBox>
                            </td>
                            <td align="right" style="width:24%; height: 27px;">
                                <asp:Label ID="lblSegDesc7" runat="server" Font-Size="9pt">Account No. :</asp:Label>
                            </td>
                            <td align="left" style="width:28%; height: 27px;">
                                <asp:TextBox ID="txtAccountNo" runat="server" Width="95%"></asp:TextBox>
                            </td>
                        </tr>
                        
                        <tr>
                            <td align="right" style="width:21%; height: 27px; font-size: 9pt;">
                                Account Name</td>
                            <td align="left" colspan="4" style="height: 27px;">
                                <asp:TextBox ID="txtAccountName" runat="server" Width="98%"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td align="right" style="width:21%; height: 27px; font-size: 9pt;">
                                Account Type</td>
                            <td align="left" style="width:28%; height: 27px;">
                                <asp:DropDownList ID="ddlBankAccountType" runat="server" 
                                    Font-Size="8pt" Height="26px" SkinID="ddlPlain" 
                                    Width="100%">
                                    <asp:ListItem>Savings</asp:ListItem>
                                    <asp:ListItem>Current</asp:ListItem>
                                </asp:DropDownList>
                            </td>
                            <td style="width:2%; height: 27px;">
                                <asp:TextBox ID="txtBranchID" runat="server" CssClass="tbc" Font-Size="8pt" 
                                    MaxLength="2" SkinID="tbPlain" TabIndex="1" Visible="False" Width="100%"></asp:TextBox>
                            </td>
                            <td align="right" style="width:24%; height: 27px; font-size: 9pt;">
                                Status</td>
                            <td align="left" style="width:28%; height: 27px;">
                                <asp:DropDownList ID="ddlStatus" runat="server" 
                                    Font-Size="8pt" Height="26px" SkinID="ddlPlain" 
                                    Width="99%">
                                    <asp:ListItem Selected="True" Value="1">Active</asp:ListItem>
                                    <asp:ListItem Value="0">InActive</asp:ListItem>
                                </asp:DropDownList>
                            </td>
                        </tr>
                        
                        <tr>
                            <td align="right" style="width:21%; height: 27px;">
                                <asp:Label ID="lblSegDesc3" runat="server" Font-Size="9pt">Address 1 :</asp:Label>
                            </td>
                            <td align="left" colspan="4" style="height: 27px;">
                                <asp:TextBox ID="txtAddress1" runat="server" Width="98%"></asp:TextBox>
                            </td>
                        </tr>
                        
                        <tr>
                            <td align="right" style="width: 21%; height: 27px;">
                                <asp:Label ID="lblSegDesc6" runat="server" Font-Size="9pt">Address 2 :</asp:Label>
                            </td>
                            <td align="left" colspan="4" style="height: 27px;">
                                <asp:TextBox ID="txtAddress2" runat="server" Width="98%"></asp:TextBox>
                            </td>
                        </tr>
                        
                        <tr>
                            <td style="width:21%; height: 30px;" align="right">
                                <asp:Label ID="lblSegDesc4" runat="server" Font-Size="9pt">Phone 1 :</asp:Label>
                            </td>
                            <td style="width:28%; height: 30px;" align="left">
                                <asp:TextBox ID="txtPhone1" runat="server" Width="100%" 
                                     onFocus="this.select()"  
                                    style="text-align:right"></asp:TextBox>
                            </td>
                            <td style="width:2%; height: 30px;">
                                </td>
                            <td style="width:24%; height: 30px;" align="right">
                                <asp:Label ID="lblSegDesc5" runat="server" Font-Size="9pt">Phone 1 :</asp:Label>
                            </td>
                            <td style="width:28%; height: 30px;" align="left">
                                <asp:TextBox ID="txtPhone2" runat="server" Width="95%" 
                                     onFocus="this.select()" 
                                    style="text-align:right"></asp:TextBox>
                            </td>
                        </tr>
                        
                        <tr>
                            <td align="right" style="width:21%; height: 30px;">
                                <asp:Label ID="lblSegCode1" runat="server" Font-Size="8pt">Segment Code</asp:Label>
                            </td>
                            <td align="left" style="width:28%; height: 30px;">
                                <asp:TextBox ID="txtBrSegCode" runat="server" AutoPostBack="False" 
                                    Font-Size="8pt" MaxLength="7" SkinID="tbGray" Width="100%"></asp:TextBox>
                            </td>
                            <td style="width:2%; height: 30px;">
                                &nbsp;</td>
                            <td align="right" style="width:24%; height: 30px;">
                                <asp:Label ID="lblParentCode1" runat="server" Font-Size="8pt">Parent Code</asp:Label>
                            </td>
                            <td align="left" style="width:28%; height: 30px;">
                                <asp:TextBox ID="txtBrParentCode" runat="server" AutoPostBack="False" 
                                    Font-Size="8pt" MaxLength="7" SkinID="tbGray" Width="95%" OnTextChanged="txtBrParentCode_TextChanged"></asp:TextBox>
                            </td>
                        </tr>
                        
                        <tr>
                            <td align="right" style="width:21%; height: 30px;">
                                <asp:Label ID="lblBankCharge" runat="server" Font-Size="8pt" Visible="False">Bank Charge</asp:Label>
                            </td>
                            <td align="left" style="width:28%; height: 30px;">
                                <asp:TextBox ID="txtBankCharge" runat="server" autocomplete="off" 
                                    AutoPostBack="true" CssClass="tbc" Font-Size="8pt" 
                                    onkeypress="return isNumber(event)" 
                                    SkinId="tbPlain" Width="100%" Visible="False">0.00</asp:TextBox>
                            </td>
                            <td style="width:2%; height: 30px;">
                                &nbsp;</td>
                            <td align="right" style="width:24%; height: 30px;">
                                &nbsp;</td>
                            <td align="left" style="width:28%; height: 30px;">
                                &nbsp;</td>
                        </tr>
                        
                        </table>

</asp:Panel>
<%--</ContentTemplate>
</asp:UpdatePanel>--%>

</div>
</fieldset>
</td>
</tr>
<tr>
<td style="height:15px; text-align:center; " colspan="3" align="center">
       
    </td>
    </tr>
<tr>
<td style="height:15px; " colspan="3">
        <asp:GridView ID="dgBranch" runat="server" Width="100%"  
            PagerStyle-CssClass="pgr" AlternatingRowStyle-CssClass="alt"  
            BorderStyle="Solid" BorderWidth="1px"
            AutoGenerateColumns="False" CssClass="mGrid" PageSize="20" 
            onrowdatabound="dgBranch_RowDataBound" 
            onselectedindexchanged="dgBranch_SelectedIndexChanged">
            
<AlternatingRowStyle CssClass="alt"></AlternatingRowStyle>
            
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="ID" HeaderText="Branch ID" />
<asp:BoundField DataField="BANK_NAME" HeaderText="Bank Name"></asp:BoundField>
                <asp:BoundField DataField="branch_name" HeaderText="Branch Name" />
                <asp:BoundField DataField="AccountNo" HeaderText="Account No" />
                <asp:BoundField DataField="addr1" HeaderText="Address" />
                <asp:BoundField DataField="phone1" HeaderText="Phone" />
                <asp:BoundField DataField="Gl_Code" HeaderText="Segment Code" />
            </Columns>

<PagerStyle CssClass="pgr"></PagerStyle>
        </asp:GridView>
<asp:GridView CssClass="mGrid" PagerStyle-CssClass="pgr"  AlternatingRowStyle-CssClass="alt" 
ID="dgBank" runat="server" AutoGenerateColumns="False" Visible="False" Width="100%" 
            BackColor="White" BorderWidth="1px" BorderStyle="Solid"
        CellPadding="2" BorderColor="LightGray" 
        Font-Size="8pt"  PageSize="20" AllowSorting="True"  ForeColor="#333333" 
            onrowdatabound="dgBank_RowDataBound" 
            onselectedindexchanged="dgBank_SelectedIndexChanged" 
            onpageindexchanging="dgBank_PageIndexChanging" >
  <Columns>
  <asp:CommandField ShowSelectButton="True"  ItemStyle-Width="100px" 
          ItemStyle-HorizontalAlign="Center" ItemStyle-ForeColor="Blue">
<ItemStyle HorizontalAlign="Center" ForeColor="Blue" Width="100px"></ItemStyle>
      </asp:CommandField>
  <asp:BoundField  HeaderText="Bank ID" DataField="bank_id" ItemStyle-Width="100px" 
          ItemStyle-HorizontalAlign="Center">
<ItemStyle HorizontalAlign="Center" Width="100px"></ItemStyle>
      </asp:BoundField>
  <asp:BoundField  HeaderText="Bank Name" DataField="bank_name" 
          ItemStyle-Width="500px" ItemStyle-HorizontalAlign="Left">  
<ItemStyle HorizontalAlign="Left" Width="40%"></ItemStyle>
      </asp:BoundField>
      <asp:BoundField DataField="Gl_Code" HeaderText="Gl_Code" />
      <asp:BoundField DataField="ParentCode" HeaderText="Parent Code" />
      <asp:BoundField DataField="BankType" HeaderText="Type" />
  </Columns>
                        <RowStyle BackColor="white" />
                        <EditRowStyle BackColor="" />
                        <PagerStyle BackColor="" HorizontalAlign="Center" />
                        <HeaderStyle BackColor="Silver" Font-Bold="True" ForeColor="Black" />
                        <AlternatingRowStyle BackColor="" />
</asp:GridView>
       <br />
    </td>
  </tr>
<tr>
<td align="center" colspan="3">
    &nbsp;</td>
</tr>
</table>
</td>
<td style="width:1%;"></td>
</tr>
</table>
</div>
</asp:Content>

